/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college.planner;

import java.awt.Color;
import java.awt.Image;
import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
public class MainFrame extends javax.swing.JFrame {
    DefaultListModel<String> smstr = new DefaultListModel<>();
    public MainFrame() throws IOException {
        initComponents();
        jList1.setModel(smstr);
        this.setLocationRelativeTo(null);
        load();
        changePanel("Login");
        
        setIconImage(ImageIO.read(new File("src/img/logo.png")));
        
        Image iimgLogo = ImageIO.read(new File("src/img/logo.png")).getScaledInstance(Login_Icon.getWidth(), Login_Icon.getHeight(), Image.SCALE_SMOOTH);
        Image iimgBack = ImageIO.read(new File("src/img/back.png")).getScaledInstance(Register_Back.getWidth(), Register_Back.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imgBack = new ImageIcon(iimgBack);
        ImageIcon imgLogo = new ImageIcon(iimgLogo);
        
        Register_Back.setIcon(imgBack);
        Login_Icon.setIcon(imgLogo);
        Home_Logo.setIcon(imgLogo);
    }
    ArrayList<db_User> db = new ArrayList<>();
    int id = -1;
    /**
     *
     * @param panel
     * Ganti-ganti panel disini
     * "Login" / "Register" / "Home"
     */
    public void changePanel(String panel){
        Login.setVisible(false);
        Register.setVisible(false);
        Home.setVisible(false);
        if (panel.equals("Login")) {
            Login.setVisible(true);
        }
        else if(panel.equals("Register")){
            Register.setVisible(true);
        }
        else if(panel.equals("Home")){
            Home.setVisible(true);
        }
        else{
            System.exit(0);
        }
    }
    
    public void load(){
        try{
            FileInputStream fin = new FileInputStream("src/data/data.ser");
            ObjectInputStream ois = new ObjectInputStream(fin);
            db = (ArrayList<db_User>) ois.readObject();
            ois.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    public void save(){
        try{
            FileOutputStream fout = new FileOutputStream("src/data/data.ser");
            ObjectOutputStream oos = new ObjectOutputStream(fout);
            oos.writeObject(db);
            oos.close();
            System.out.println("Saved");

       }catch(Exception e){
            System.out.println(e);
       }
    }
    
    public void refreshHome(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register_ButtonGroup = new javax.swing.ButtonGroup();
        Register = new javax.swing.JPanel();
        Register_Container = new javax.swing.JPanel();
        Register_LabelUsername = new javax.swing.JLabel();
        Register_Username = new javax.swing.JTextField();
        Register_LabelPassword = new javax.swing.JLabel();
        Register_FirstName = new javax.swing.JTextField();
        Register_Password1 = new javax.swing.JPasswordField();
        Register_Password2 = new javax.swing.JPasswordField();
        Register_LabelConfirmPassword = new javax.swing.JLabel();
        Register_LabelFirstName = new javax.swing.JLabel();
        Register_LastName = new javax.swing.JTextField();
        Register_LabelLastName = new javax.swing.JLabel();
        Register_LabelDate = new javax.swing.JLabel();
        Register_ButtonRegister = new javax.swing.JButton();
        Register_LabelGender = new javax.swing.JLabel();
        Register_RadioMale = new javax.swing.JRadioButton();
        Register_RadioFemale = new javax.swing.JRadioButton();
        Register_CheckTOS = new javax.swing.JCheckBox();
        Register_DatePicker = new com.github.lgooddatepicker.components.DatePicker();
        Register_LabelEmail = new javax.swing.JLabel();
        Register_Email = new javax.swing.JTextField();
        Register_LabelTitle = new javax.swing.JLabel();
        Register_Back = new javax.swing.JButton();
        Login = new javax.swing.JPanel();
        Login_Container = new javax.swing.JPanel();
        Login_Username = new javax.swing.JTextField();
        Login_LabelUsername = new javax.swing.JLabel();
        Login_LabelPassword = new javax.swing.JLabel();
        Login_ButtonLogin = new javax.swing.JButton();
        Login_Password = new javax.swing.JPasswordField();
        Login_Container_Reg = new javax.swing.JPanel();
        Login_LabelDontHaveAnAcc = new javax.swing.JLabel();
        Login_Icon = new javax.swing.JLabel();
        Login_Register = new javax.swing.JButton();
        Home = new javax.swing.JPanel();
        Home_Menu = new javax.swing.JPanel();
        Home_Logo = new javax.swing.JLabel();
        Home_Semester = new javax.swing.JButton();
        Home_Agenda = new javax.swing.JButton();
        Home_Setting = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Home_Semester1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Setting = new javax.swing.JPanel();
        Agenda = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("College Planner");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        Register.setBackground(new java.awt.Color(255, 255, 255));
        Register.setMaximumSize(new java.awt.Dimension(800, 600));
        Register.setMinimumSize(new java.awt.Dimension(800, 600));
        Register.setPreferredSize(new java.awt.Dimension(800, 600));

        Register_Container.setBackground(new java.awt.Color(255, 255, 255));

        Register_LabelUsername.setText("Username");
        Register_LabelUsername.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Register_Username.setPreferredSize(new java.awt.Dimension(6, 25));

        Register_LabelPassword.setText("Password");
        Register_LabelPassword.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_FirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Register_Password1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Register_Password1.setPreferredSize(new java.awt.Dimension(6, 25));

        Register_Password2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Register_Password2.setPreferredSize(new java.awt.Dimension(6, 25));

        Register_LabelConfirmPassword.setText("Confirm Password");
        Register_LabelConfirmPassword.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_LabelFirstName.setText("First Name");
        Register_LabelFirstName.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_LastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Register_LabelLastName.setText("Last Name");
        Register_LabelLastName.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_LabelDate.setText("Date of Birth");
        Register_LabelDate.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_ButtonRegister.setBackground(new java.awt.Color(1, 148, 72));
        Register_ButtonRegister.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Register_ButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        Register_ButtonRegister.setText("Register");
        Register_ButtonRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register_ButtonRegister.setBorderPainted(false);
        Register_ButtonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register_ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonRegisterActionPerformed(evt);
            }
        });

        Register_LabelGender.setText("Gender");
        Register_LabelGender.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_RadioMale.setBackground(new java.awt.Color(255, 255, 255));
        Register_ButtonGroup.add(Register_RadioMale);
        Register_RadioMale.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Register_RadioMale.setSelected(true);
        Register_RadioMale.setText("Male");

        Register_RadioFemale.setBackground(new java.awt.Color(255, 255, 255));
        Register_ButtonGroup.add(Register_RadioFemale);
        Register_RadioFemale.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Register_RadioFemale.setText("Female");

        Register_CheckTOS.setText("I Agree to the Terms of Use");
        Register_CheckTOS.setBackground(new java.awt.Color(255, 255, 255));
        Register_CheckTOS.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        Register_DatePicker.setBackground(new java.awt.Color(255, 255, 255));
        Register_DatePicker.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Register_LabelEmail.setText("Email");
        Register_LabelEmail.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Register_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Register_Email.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout Register_ContainerLayout = new javax.swing.GroupLayout(Register_Container);
        Register_Container.setLayout(Register_ContainerLayout);
        Register_ContainerLayout.setHorizontalGroup(
            Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Register_CheckTOS)
                    .addGroup(Register_ContainerLayout.createSequentialGroup()
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Register_ContainerLayout.createSequentialGroup()
                                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Register_LabelPassword)
                                    .addComponent(Register_LabelEmail)
                                    .addComponent(Register_LabelUsername))
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Register_ContainerLayout.createSequentialGroup()
                                .addComponent(Register_LabelConfirmPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Register_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Register_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Register_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Register_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Register_ButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Register_ContainerLayout.createSequentialGroup()
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Register_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Register_LabelFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Register_LabelLastName)
                            .addComponent(Register_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Register_ContainerLayout.createSequentialGroup()
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Register_LabelDate)
                            .addGroup(Register_ContainerLayout.createSequentialGroup()
                                .addComponent(Register_LabelGender)
                                .addGap(16, 16, 16)
                                .addComponent(Register_RadioMale)))
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Register_ContainerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Register_RadioFemale))
                            .addGroup(Register_ContainerLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Register_DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Register_ContainerLayout.setVerticalGroup(
            Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Register_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register_LabelFirstName)
                    .addComponent(Register_LabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Register_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Register_LabelDate)
                    .addComponent(Register_DatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Register_ContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Register_LabelGender)
                            .addComponent(Register_RadioMale)
                            .addComponent(Register_RadioFemale)))
                    .addGroup(Register_ContainerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Register_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Register_LabelEmail))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Register_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Register_LabelUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register_LabelPassword)
                    .addComponent(Register_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Register_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register_LabelConfirmPassword)
                    .addComponent(Register_Password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Register_CheckTOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Register_ButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Register_LabelTitle.setText("Create New Account");
        Register_LabelTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N

        Register_Back.setBackground(new java.awt.Color(255, 255, 255));
        Register_Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register_Back.setBorderPainted(false);
        Register_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register_Back.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Register_Back.setForeground(new java.awt.Color(255, 255, 255));
        Register_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Register_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Register_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158)
                        .addComponent(Register_LabelTitle)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Register_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Register_LabelTitle)))
                .addGap(13, 13, 13)
                .addComponent(Register_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );

        getContentPane().add(Register, "card3");

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setMaximumSize(new java.awt.Dimension(800, 600));
        Login.setMinimumSize(new java.awt.Dimension(800, 600));
        Login.setPreferredSize(new java.awt.Dimension(800, 600));

        Login_Container.setBackground(new java.awt.Color(255, 255, 255));

        Login_Username.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        Login_LabelUsername.setText("Username");
        Login_LabelUsername.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Login_LabelPassword.setText("Password");
        Login_LabelPassword.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Login_ButtonLogin.setText("Log In");
        Login_ButtonLogin.setBackground(new java.awt.Color(1, 148, 72));
        Login_ButtonLogin.setBorderPainted(false);
        Login_ButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_ButtonLogin.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Login_ButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        Login_ButtonLogin.setToolTipText("");
        Login_ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonLoginActionPerformed(evt);
            }
        });

        Login_Password.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        javax.swing.GroupLayout Login_ContainerLayout = new javax.swing.GroupLayout(Login_Container);
        Login_Container.setLayout(Login_ContainerLayout);
        Login_ContainerLayout.setHorizontalGroup(
            Login_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Login_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Login_Password)
                    .addComponent(Login_ButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Login_LabelPassword)
                    .addComponent(Login_LabelUsername)
                    .addComponent(Login_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Login_ContainerLayout.setVerticalGroup(
            Login_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login_LabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login_LabelPassword)
                .addGap(1, 1, 1)
                .addComponent(Login_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login_ButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Login_Container_Reg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Login_Container_RegLayout = new javax.swing.GroupLayout(Login_Container_Reg);
        Login_Container_Reg.setLayout(Login_Container_RegLayout);
        Login_Container_RegLayout.setHorizontalGroup(
            Login_Container_RegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        Login_Container_RegLayout.setVerticalGroup(
            Login_Container_RegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Login_LabelDontHaveAnAcc.setText("Dont't have an account?");
        Login_LabelDontHaveAnAcc.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N

        Login_Register.setText("Register");
        Login_Register.setBackground(new java.awt.Color(1, 148, 72));
        Login_Register.setBorderPainted(false);
        Login_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_Register.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Login_Register.setForeground(new java.awt.Color(255, 255, 255));
        Login_Register.setToolTipText("");
        Login_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(Login_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(Login_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(Login_Container_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                        .addComponent(Login_LabelDontHaveAnAcc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Login_Register)
                        .addGap(42, 42, 42))))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Login_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Login_LabelDontHaveAnAcc))
                .addGap(51, 51, 51)
                .addComponent(Login_Container_Reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Login, "card2");

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setFont(getFont());
        Home.setMaximumSize(new java.awt.Dimension(800, 600));
        Home.setMinimumSize(new java.awt.Dimension(800, 600));
        Home.setPreferredSize(new java.awt.Dimension(800, 600));

        Home_Semester.setText("Semester");
        Home_Semester.setBackground(new java.awt.Color(0, 92, 45));
        Home_Semester.setBorder(null);
        Home_Semester.setBorderPainted(false);
        Home_Semester.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_Semester.setFocusPainted(false);
        Home_Semester.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Home_Semester.setForeground(new java.awt.Color(255, 255, 255));

        Home_Agenda.setText("Agenda");
        Home_Agenda.setBackground(new java.awt.Color(1, 148, 72));
        Home_Agenda.setBorder(null);
        Home_Agenda.setBorderPainted(false);
        Home_Agenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_Agenda.setFocusPainted(false);
        Home_Agenda.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Home_Agenda.setForeground(new java.awt.Color(255, 255, 255));

        Home_Setting.setText("Setting");
        Home_Setting.setBackground(new java.awt.Color(1, 148, 72));
        Home_Setting.setBorder(null);
        Home_Setting.setBorderPainted(false);
        Home_Setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_Setting.setFocusPainted(false);
        Home_Setting.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Home_Setting.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Home_MenuLayout = new javax.swing.GroupLayout(Home_Menu);
        Home_Menu.setLayout(Home_MenuLayout);
        Home_MenuLayout.setHorizontalGroup(
            Home_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Home_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Home_Setting, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(Home_Agenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home_Logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home_Semester, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        Home_MenuLayout.setVerticalGroup(
            Home_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Home_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Home_Agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Home_Setting, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Home_Semester.getAccessibleContext().setAccessibleName("Home Semester");

        jLabel4.setText("Semester");
        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N

        Home_Semester1.setText("Add Semester");
        Home_Semester1.setBackground(new java.awt.Color(1, 148, 72));
        Home_Semester1.setBorder(null);
        Home_Semester1.setBorderPainted(false);
        Home_Semester1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home_Semester1.setFocusPainted(false);
        Home_Semester1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Home_Semester1.setForeground(new java.awt.Color(255, 255, 255));
        Home_Semester1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_Semester1ActionPerformed(evt);
            }
        });

        jList1.setSelectionBackground(new java.awt.Color(1, 148, 72));
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(Home_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Home_Semester1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addContainerGap())
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Home_Semester1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Home, "card4");

        javax.swing.GroupLayout SettingLayout = new javax.swing.GroupLayout(Setting);
        Setting.setLayout(SettingLayout);
        SettingLayout.setHorizontalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        SettingLayout.setVerticalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Setting, "card6");

        javax.swing.GroupLayout AgendaLayout = new javax.swing.GroupLayout(Agenda);
        Agenda.setLayout(AgendaLayout);
        AgendaLayout.setHorizontalGroup(
            AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        AgendaLayout.setVerticalGroup(
            AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(Agenda, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonLoginActionPerformed
        if (Login_Username.getText().isEmpty() || Login_Password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Semua field harus di isi", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (Login_Password.getPassword().length < 8) {
            JOptionPane.showMessageDialog(rootPane, "Password minimal 8 karakter", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            load();
            int idTemp = -1;
            for (int i = 0; i < db.size(); i++) {
                if (Login_Username.getText().equals(db.get(i).getUsername())) {
                    idTemp = i;
                    break;
                }
            }
            if (idTemp != -1) {
                if (Login_Password.getText().equals(db.get(idTemp).getPassword())) {
                    id = idTemp;
                    changePanel("Home");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Username / Password salah", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Username / Password salah", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Login_ButtonLoginActionPerformed

    private void Register_ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonRegisterActionPerformed
        EmailValidator emailValidator = new EmailValidator();
        if (Register_Username.getText().isEmpty() || Register_Email.getText().isEmpty()
                || Register_Password1.getText().isEmpty() || Register_Password2.getText().isEmpty()
                || Register_DatePicker.getDateStringOrEmptyString().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Semua field harus di isi", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(!emailValidator.validate(Register_Email.getText().trim())) {
             JOptionPane.showMessageDialog(rootPane, "Email tidak valid", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (Register_Password1.getPassword().length < 8) {
            JOptionPane.showMessageDialog(rootPane, "Password minimal 8 karakter", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (!Arrays.equals(Register_Password1.getPassword(), Register_Password2.getPassword())) {
            JOptionPane.showMessageDialog(rootPane, "Password tidak sama", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (Register_DatePicker.getDateStringOrEmptyString().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Date invalid", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (!Register_CheckTOS.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Harus setuju TOS", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            load();
            boolean sama = false;
            for (int i = 0; i < db.size(); i++) {
                if (Register_Username.getText().equalsIgnoreCase(db.get(i).getUsername())) {
                    sama = true;
                    break;
                }
            }
            if (!sama){
                String gender = "Female";
                if (Register_RadioMale.isSelected()){gender = "Male";}
                db.add(new db_User(Register_Username.getText(), Register_Password1.getText(), Register_FirstName.getText(), Register_LastName.getText(), Register_DatePicker.getDateStringOrEmptyString(), gender, Register_Email.getText()));
                save();
                Register_RadioMale.setSelected(true);
                Register_FirstName.setText("");
                Register_LastName.setText("");
                Register_Email.setText("");
                Register_Username.setText("");
                Register_Password1.setText("");
                Register_Password2.setText("");
                Register_DatePicker.setDateToToday();
                Register_CheckTOS.setSelected(false);
                JOptionPane.showMessageDialog(rootPane, "Register berhasil!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Username sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Register_ButtonRegisterActionPerformed

    private void Register_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_BackActionPerformed
        changePanel("Login");
    }//GEN-LAST:event_Register_BackActionPerformed

    private void Login_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_RegisterActionPerformed
        changePanel("Register");
    }//GEN-LAST:event_Login_RegisterActionPerformed

    private void Home_Semester1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_Semester1ActionPerformed
        //String year = JOptionPane.showInputDialog(rootPane, "What year?", "Add Semester", JOptionPane.QUESTION_MESSAGE);
        String semester = JOptionPane.showInputDialog(rootPane, "What semester?", "Add Semester", JOptionPane.QUESTION_MESSAGE);
        int kembar = 0;
        for (int i = 0; i < jList1.getModel().getSize(); i++){
            Object isi = jList1.getModel().getElementAt(i);
            String sudah = (String) isi;
            if (semester.equals(sudah)){
                kembar = 1;
            }
        }
        if (kembar == 0){
            smstr.addElement(semester);
            String[] tampung = new String[jList1.getModel().getSize()];
            int ctr = 0;
            for (int i = 0; i < jList1.getModel().getSize(); i++){
                Object isi = jList1.getModel().getElementAt(i);
                String sudah = (String) isi;
                tampung[ctr] = sudah;
                ctr++;
            }
            smstr.removeAllElements();
            for (int i = 0; i < tampung.length-1; i++)
            {
                for (int j = i+i; j < tampung.length; j++)
                {
                    if (tampung[i].compareTo(tampung[j])>0) // >0  <0  =
                    {
                        String temp = tampung[i];
                        tampung[i] = tampung[j];
                        tampung[j]=temp;
                    }
                }
            }
            for (int i = 0; i < tampung.length; i++){
                smstr.addElement(tampung[i]);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Semester sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
            
    }//GEN-LAST:event_Home_Semester1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agenda;
    private javax.swing.JPanel Home;
    private javax.swing.JButton Home_Agenda;
    private javax.swing.JLabel Home_Logo;
    private javax.swing.JPanel Home_Menu;
    private javax.swing.JButton Home_Semester;
    private javax.swing.JButton Home_Semester1;
    private javax.swing.JButton Home_Setting;
    private javax.swing.JPanel Login;
    private javax.swing.JButton Login_ButtonLogin;
    private javax.swing.JPanel Login_Container;
    private javax.swing.JPanel Login_Container_Reg;
    private javax.swing.JLabel Login_Icon;
    private javax.swing.JLabel Login_LabelDontHaveAnAcc;
    private javax.swing.JLabel Login_LabelPassword;
    private javax.swing.JLabel Login_LabelUsername;
    private javax.swing.JPasswordField Login_Password;
    private javax.swing.JButton Login_Register;
    private javax.swing.JTextField Login_Username;
    private javax.swing.JPanel Register;
    private javax.swing.JButton Register_Back;
    private javax.swing.ButtonGroup Register_ButtonGroup;
    private javax.swing.JButton Register_ButtonRegister;
    private javax.swing.JCheckBox Register_CheckTOS;
    private javax.swing.JPanel Register_Container;
    private com.github.lgooddatepicker.components.DatePicker Register_DatePicker;
    private javax.swing.JTextField Register_Email;
    private javax.swing.JTextField Register_FirstName;
    private javax.swing.JLabel Register_LabelConfirmPassword;
    private javax.swing.JLabel Register_LabelDate;
    private javax.swing.JLabel Register_LabelEmail;
    private javax.swing.JLabel Register_LabelFirstName;
    private javax.swing.JLabel Register_LabelGender;
    private javax.swing.JLabel Register_LabelLastName;
    private javax.swing.JLabel Register_LabelPassword;
    private javax.swing.JLabel Register_LabelTitle;
    private javax.swing.JLabel Register_LabelUsername;
    private javax.swing.JTextField Register_LastName;
    private javax.swing.JPasswordField Register_Password1;
    private javax.swing.JPasswordField Register_Password2;
    private javax.swing.JRadioButton Register_RadioFemale;
    private javax.swing.JRadioButton Register_RadioMale;
    private javax.swing.JTextField Register_Username;
    private javax.swing.JPanel Setting;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
